version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    user: root
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 111222333
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 30s
      timeout: 30s
      retries: 3